version: '3.8'  # You can specify a version or remove this line as it's now deprecated

services:
  postgis:
    image: kartoza/postgis:latest  # Corrected the image name here
    container_name: postgis
    restart: always
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pgrouting
    volumes:
      - dbbackup:/backup
      - postgis-data:/var/lib/postgresql/data  # Ensure this volume is defined

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgis
    volumes:
      - dbbackup:/backup

volumes:
  dbbackup:
  postgis-data:
